networks:
  kong-net:
    name: compose_kong-net
    external: true
      

services:
  auth-service:
    build: ./auth-service
    ports:
      - "1323:1323"
    networks:
      - kong-net

  lgtm:
    image: grafana/otel-lgtm
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3000:3000"
    networks:
      - kong-net

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"
    networks:
      - kong-net
  
  python-service:
    build: ./python-service
    ports:
      - "9001:8000"
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=python-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://lgtm:4318/v1/traces
    networks:
      - kong-net